cartesi/rollups-contracts

.github/ISSUE_TEMPLATE/update-dependencies.md

fix: adapt `update-dependencies.md`

---

CHANGELOG.md

docs: add link to unreleased diff in CHANGELOG

---

.github/workflows/check-code-format.yml
.github/workflows/check-commit-messages.yml
CODEOWNERS

feat: improve workflows

---

onchain/rollups/foundry.toml
onchain/rollups/test/foundry/dapp/CartesiDApp.t.sol

feat: make `CartesiDApp.t.sol` remove any extra input JSON files

---

.github/workflows/build.yml
.github/workflows/check-code-format.yml
.github/workflows/publish.yml
CHANGELOG.md
onchain/rollups/package.json

feat: publish `@cartesi/rollups` through GitHub Actions

---

CHANGELOG.md
onchain/rollups/contracts/consensus/authority/AuthorityFactory.sol
onchain/rollups/contracts/consensus/authority/IAuthorityFactory.sol
onchain/rollups/deploy/02_factory.ts
onchain/rollups/test/foundry/consensus/authority/AuthorityFactory.t.sol

feat: authority factory

---

CHANGELOG.md
onchain/rollups/contracts/history/HistoryFactory.sol
onchain/rollups/contracts/history/IHistoryFactory.sol
onchain/rollups/deploy/02_factory.ts
onchain/rollups/test/foundry/history/HistoryFactory.t.sol

feat: history factory

---

CHANGELOG.md
onchain/rollups/contracts/consensus/authority/AuthorityHistoryPairFactory.sol
onchain/rollups/contracts/consensus/authority/IAuthorityHistoryPairFactory.sol
onchain/rollups/deploy/02_factory.ts
onchain/rollups/test/foundry/consensus/authority/AuthorityHistoryPairFactory.t.sol

feat: authority-history pair factory

---

onchain/rollups/test/foundry/consensus/authority/AuthorityFactory.t.sol
onchain/rollups/test/foundry/consensus/authority/AuthorityHistoryPairFactory.t.sol
onchain/rollups/test/foundry/dapp/CartesiDAppFactory.t.sol
onchain/rollups/test/foundry/history/HistoryFactory.t.sol

Thanks for the insight, @xdaniortega !
Closes #108

feat: decode event data with struct

---

onchain/rollups/contracts/consensus/quorum/Quorum.sol

Renames:
- `validatorIndex` :arrow_right: `validatorId`
Adds:
- `validatorById`
- `validators`
- `numOfValidatorsInFavorOf`
- `isValidatorInFavorOf`
- `validatorsInFavorOf`

feat: improve quorum

---

.github/workflows/test.yml

ci: upload signatures

---

onchain/rollups/.changeset/cool-suits-lick.md
onchain/rollups/.changeset/lucky-kings-switch.md
onchain/rollups/contracts/dapp/CartesiDApp.sol
onchain/rollups/contracts/dapp/ICartesiDApp.sol
onchain/rollups/test/foundry/dapp/CartesiDApp.t.sol

feat: propagate errors on voucher execution

---

onchain/rollups/.changeset/plenty-feet-help.md
onchain/rollups/.changeset/tough-shoes-taste.md
onchain/rollups/contracts/common/InputEncoding.sol
onchain/rollups/contracts/portals/ERC20Portal.sol
onchain/rollups/test/foundry/portals/ERC20Portal.t.sol

feat: reject failed ERC-20 transfers

---

onchain/rollups/.changeset/clean-spies-deny.md
onchain/rollups/.changeset/grumpy-cooks-watch.md
onchain/rollups/.changeset/mean-cars-applaud.md
onchain/rollups/.changeset/three-pigs-flow.md
onchain/rollups/contracts/common/InputRange.sol
onchain/rollups/contracts/common/OutputValidityProof.sol
onchain/rollups/contracts/common/Proof.sol
onchain/rollups/contracts/consensus/AbstractConsensus.sol
onchain/rollups/contracts/consensus/IConsensus.sol
onchain/rollups/contracts/consensus/authority/Authority.sol
onchain/rollups/contracts/dapp/CartesiDApp.sol
onchain/rollups/contracts/dapp/ICartesiDApp.sol
onchain/rollups/contracts/library/LibInputRange.sol
onchain/rollups/contracts/library/LibOutputValidation.sol
onchain/rollups/contracts/library/LibProof.sol
onchain/rollups/test/foundry/consensus/authority/Authority.t.sol
onchain/rollups/test/foundry/dapp/CartesiDApp.t.sol
onchain/rollups/test/foundry/util/LibServerManager.sol
onchain/rollups/test/foundry/util/SimpleConsensus.sol

Closes #152 and #153
FYI @gligneul

feat!: new `IConsensus` interface

---

onchain/rollups/test/foundry/portals/ERC1155BatchPortal.t.sol
onchain/rollups/test/foundry/portals/ERC1155SinglePortal.t.sol
onchain/rollups/test/foundry/portals/ERC20Portal.t.sol
onchain/rollups/test/foundry/portals/ERC721Portal.t.sol

add integrated tests for portals with Openzepplin's token implementations, for extra safety and more thorough test suites

test: add integrated token tests for portals

---

.github/workflows/release.yml

ci: use bot account PAT for release workflow

---

onchain/rollups/test/foundry/consensus/quorum/Quorum.t.sol
onchain/rollups/test/foundry/consensus/quorum/QuorumFactory.t.sol
onchain/rollups/test/foundry/util/TestBase.sol

The following changes are made:
- bump pragma version for tests in order to allow foreign access to events
- comply with solidity style guide

improve quorum and factory tests

---

README.md

Document how to deploy the contracts to a local network.

docs: deployment

---

onchain/rollups/contracts/common/InputRange.sol
onchain/rollups/contracts/dapp/Application.sol
onchain/rollups/contracts/dapp/IApplication.sol
onchain/rollups/contracts/library/LibProof.sol
onchain/rollups/test/foundry/dapp/Application.t.sol
onchain/rollups/test/foundry/util/LibServerManager.sol

refactor!: type input indices as `uint64`

---

onchain/rollups/.changeset/odd-sloths-tie.md
onchain/rollups/.changeset/tough-shoes-taste.md
onchain/rollups/.changeset/twelve-dragons-lie.md
onchain/rollups/contracts/portals/EtherPortal.sol
onchain/rollups/contracts/portals/IEtherPortal.sol
onchain/rollups/test/foundry/portals/EtherPortal.t.sol

- Revert change in `EtherPortal` (parameter `dapp` doesn't need to be `payable` anymore)
- Remove/edit changeset files

fix: adjust changes to portal

---

onchain/rollups/.changeset/silly-islands-end.md
onchain/rollups/contracts/dapp/Application.sol
onchain/rollups/contracts/dapp/IApplication.sol
onchain/rollups/test/foundry/dapp/Application.t.sol

feat!: add `output` parameter to `OutputExecuted` event

---

.github/workflows/release.yml
.github/workflows/test.yml

Adjust CI to run on pre-release branches

---

CONTRACTS.md
onchain/rollups/.changeset/purple-dolphins-nail.md
onchain/rollups/.changeset/red-wasps-report.md
onchain/rollups/contracts/common/Outputs.sol
onchain/rollups/contracts/dapp/Application.sol
onchain/rollups/test/foundry/dapp/Application.t.sol

feat!: allow vouchers to transfer Ether

---

.github/workflows/check-code-format.yml
.github/workflows/check-commit-messages.yml
.github/workflows/release.yml
.github/workflows/test.yml

ci: generate and publish Rust bindings

---

onchain/rollups/.changeset/clean-gorillas-occur.md
onchain/rollups/contracts/common/CanonicalMachine.sol

fix: adjust maximum input size

---

onchain/rollups/test/foundry/dapp/Application.t.sol
onchain/rollups/test/foundry/portals/ERC1155BatchPortal.t.sol
onchain/rollups/test/foundry/portals/ERC1155SinglePortal.t.sol
onchain/rollups/test/foundry/portals/ERC20Portal.t.sol
onchain/rollups/test/foundry/portals/ERC721Portal.t.sol
onchain/rollups/test/foundry/portals/EtherPortal.t.sol
onchain/rollups/test/foundry/util/ERC165Test.sol

test: EIP-165 contracts

---

onchain/rollups/.changeset/pre.json

Ran `yarn changeset pre enter rc`.

chore: enter pre-release mode (tag `rc`)

---

.github/workflows/docs.yml
README.md

ci: deploy documentation

---

contracts/common/InputEncoding.sol
contracts/portals/ERC20Portal.sol
contracts/portals/IERC20Portal.sol
test/foundry/portals/ERC20Portal.t.sol

Use "value" rather than "amount" for ERC-20 deposits

---

.changeset/thirty-crews-fail.md
contracts/common/Outputs.sol
contracts/dapp/Application.sol

Add `DELEGATECALL` voucher

---

.changeset/lucky-elephants-play.md
contracts/delegatecall/SafeERC20Transfer.sol
test/foundry/dapp/Application.t.sol

I call it delegate and create the folder `delegate`.
Let me know if you think it should be named something else

safe erc20 delegate

---

package.json
pnpm-lock.yaml

Context: https://github.com/wighawag/hardhat-deploy/issues/558#issuecomment-2421720506.

chore: bump hardhat-deploy from 0.13.0 to 0.14.0

---

.github/workflows/check-code-format.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/setup/action.yml
.github/workflows/test.yml
.github/workflows/upload-artifacts.yml
.gitignore
hardhat.config.ts
src/tasks/deploy-anvil.ts

Upload Anvil deployment artifacts to GH Releases

---

.github/actions/setup/action.yml
.github/workflows/check-code-format.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/upload-artifacts.yml

Also move action to `.github/actions`, as suggested by GitHub documentation.

fix: setup action

---

.github/actions/setup/action.yml
.github/workflows/check-code-format.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/upload-artifacts.yml

Please upgrade your local Foundryup installation:
https://x.com/gakonst/status/1881802255202193584

ci: use stable release of Foundry

---

.github/workflows/upload-artifacts.yml

ci: fix typo in anvil-version ouput

---

.changeset/tasty-cherries-battle.md
cannonfile.toml
package.json
pnpm-lock.yaml

This PR just adds the Cannon CLI package as a dev dependency, and a Cannonfile.

Add Cannonfile

---

.github/workflows/upload-artifacts.yml
.gitignore
package.json

You can test the commands locally:
- `pnpm clean`
- `pnpm build:contracts`
- `pnpm build:devnet`

ci: update artifact upload workflow

---

.changeset/angry-worms-dig.md
src/inputs/IInputBox.sol
src/inputs/InputBox.sol
src/library/LibAddress.sol
test/inputs/InputBox.t.sol

Make `InputBox` require application contract deployment

---

foundry.toml
soldeer.lock
src/consensus/dave/DaveConsensus.sol
src/consensus/dave/DaveConsensusFactory.sol
test/consensus/dave/DaveConsensus.t.sol
test/consensus/dave/DaveConsensusFactory.t.sol
test/inputs/InputBox.t.sol
test/util/MockContract.sol

Preserves commit history from [`cartesi/dave`](https://github.com/cartesi/dave).
Closes #411.

Add PRT Rollups Contracts
