cartesi/rollups-contracts

- .github/workflows/build.yml
Temporary fix for https://github.com/foundry-rs/foundry/issues/5818.
> ci: use nightly version of foundry

- onchain/rollups/test/foundry/dapp/CartesiDApp.t.sol
- onchain/rollups/test/foundry/util/LibServerManager.sol
- correct the naming of `inputIndex` to `inputIndexWithinEpoch` if it's used incorrectly
- ~~abbreviate `inputIndexWithinEpoch` as `IIWE` if it's compounded with other words~~
> fix: correct the use of inputIndex in tests

- onchain/rollups/test/foundry/portals/ERC20Portal.t.sol
- onchain/rollups/test/foundry/portals/EtherPortal.t.sol
It occurred to me that sometimes github CI tests failed on portal invariant tests like [this one](https://github.com/cartesi/rollups-contracts/actions/runs/6774935288/job/18413093883?pr=121). The reason is that we used `msg.sender` as token sender, and sometimes forge assigns this random `msg.sender` an address that has already deployed a contract (e.g. the portal). This would cause the invariant test to fail because we require portal to have 0 balance all the time.
> fix portal tests address overlaps

- onchain/rollups/.changeset/wise-penguins-poke.md
Since #113 will be merged for 1.2.0, the changeset text should be a little different.
Closes #132
> docs: adjust changeset about ERC-20 deposit input

- onchain/rollups/test/foundry/dapp/CartesiDApp.t.sol
- onchain/rollups/test/foundry/util/LibBytes.sol
> test: add `LibBytes.sol`

- onchain/rollups/contracts/common/InputRange.sol
- onchain/rollups/contracts/consensus/AbstractConsensus.sol
- onchain/rollups/contracts/consensus/IConsensus.sol
- onchain/rollups/contracts/consensus/authority/Authority.sol
- onchain/rollups/contracts/library/LibInputRange.sol
- onchain/rollups/contracts/library/LibProof.sol
- onchain/rollups/test/foundry/consensus/authority/Authority.t.sol
- onchain/rollups/test/foundry/dapp/CartesiDApp.t.sol
- onchain/rollups/test/foundry/util/LibServerManager.sol
- rename `{first,last}InputIndex` as `{first,last}Index`: it is clear that the index is about the input because it is a field on the `InputRange` structure, also we save some characters.
- remove empty set check on input range: we don't need to check if the input range is empty or not, because they will be useless to validating outputs anyway, because you can't prove that it contains some input index.
> refactor: simplify consensus

- onchain/rollups/.changeset/quick-months-type.md
- onchain/rollups/foundry.toml
- onchain/rollups/hardhat.config.ts
- onchain/rollups/test/foundry/consensus/authority/Authority.t.sol
- onchain/rollups/test/foundry/consensus/authority/AuthorityFactory.t.sol
- onchain/rollups/test/foundry/dapp/Application.t.sol
- onchain/rollups/test/foundry/dapp/ApplicationFactory.t.sol
- onchain/rollups/test/foundry/inputs/InputBox.t.sol
- onchain/rollups/test/foundry/portals/ERC1155BatchPortal.t.sol
- onchain/rollups/test/foundry/portals/ERC1155SinglePortal.t.sol
- onchain/rollups/test/foundry/portals/ERC20Portal.t.sol
- onchain/rollups/test/foundry/portals/ERC721Portal.t.sol
- onchain/rollups/test/foundry/portals/EtherPortal.t.sol
- onchain/rollups/test/foundry/relays/ApplicationAddressRelay.t.sol
- onchain/rollups/test/foundry/util/LibBytes.sol
- onchain/rollups/test/foundry/util/LibServerManager.sol
- onchain/rollups/test/foundry/util/SimpleConsensus.sol
- onchain/rollups/test/foundry/util/SimpleERC20.sol
- onchain/rollups/test/foundry/util/SimpleERC721.sol
- onchain/rollups/test/foundry/util/TestBase.sol
- bump solc
- allow foreign access to events in test contracts
- upgrade pragma for test contracts to 0.8.22 (reasoning is [here](https://github.com/cartesi/rollups-contracts/issues/173#issuecomment-1864447226))
> bump solc to the latest version 0.8.23

- onchain/rollups/.changeset/pink-penguins-kiss.md
- onchain/rollups/contracts/consensus/authority/AuthorityFactory.sol
- onchain/rollups/contracts/consensus/authority/IAuthorityFactory.sol
- onchain/rollups/contracts/dapp/Application.sol
- onchain/rollups/contracts/dapp/ApplicationFactory.sol
- onchain/rollups/contracts/dapp/IApplication.sol
- onchain/rollups/contracts/dapp/IApplicationFactory.sol
- onchain/rollups/contracts/inputs/IInputBox.sol
- onchain/rollups/contracts/inputs/InputBox.sol
- onchain/rollups/contracts/inputs/InputRelay.sol
- onchain/rollups/contracts/portals/ERC1155BatchPortal.sol
- onchain/rollups/contracts/portals/ERC1155SinglePortal.sol
- onchain/rollups/contracts/portals/ERC20Portal.sol
- onchain/rollups/contracts/portals/ERC721Portal.sol
- onchain/rollups/contracts/portals/EtherPortal.sol
- onchain/rollups/contracts/portals/IERC1155BatchPortal.sol
- onchain/rollups/contracts/portals/IERC1155SinglePortal.sol
- onchain/rollups/contracts/portals/IERC20Portal.sol
- onchain/rollups/contracts/portals/IERC721Portal.sol
- onchain/rollups/contracts/portals/IEtherPortal.sol
- onchain/rollups/contracts/relays/ApplicationAddressRelay.sol
- onchain/rollups/contracts/relays/IApplicationAddressRelay.sol
- onchain/rollups/test/foundry/consensus/authority/Authority.t.sol
- onchain/rollups/test/foundry/consensus/authority/AuthorityFactory.t.sol
- onchain/rollups/test/foundry/dapp/Application.t.sol
- onchain/rollups/test/foundry/dapp/ApplicationFactory.t.sol
- onchain/rollups/test/foundry/inputs/InputBox.t.sol
- onchain/rollups/test/foundry/portals/ERC20Portal.t.sol
- onchain/rollups/test/foundry/relays/ApplicationAddressRelay.t.sol
- onchain/rollups/test/foundry/util/LibServerManager.sol
Following the [solidity style guide](https://docs.soliditylang.org/en/v0.8.23/style-guide.html), we made the following changes:
- remove prefix `_` for function parameters
- prefix `_` for internal/private state variables and functions, except for libraries, within which all functions are internal. For reference purpose, Openzeppelin also didn't prefix `_` for their [library](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol).
- order functions and contract properties following the convention summarized [here](https://github.com/cartesi/rollups-contracts/issues/164#issuecomment-1882511525), with exceptions that if it’s easier to read otherwise
> comply with solidity style guide

- README.md
- onchain/rollups/.changeset/lovely-carpets-change.md
- onchain/rollups/contracts/consensus/quorum/Quorum.sol
- onchain/rollups/test/foundry/consensus/quorum/Quorum.t.sol
- onchain/rollups/test/foundry/util/TestBase.sol
> feat: add quorum

- .github/workflows/release.yml
Tags and branches such as `v1` can be modified if the repository is compromised.
Commit hashes, on the other hand, are unfeasible to craft.
Let's adopt this security step whenever secrets (such as API tokens) are exposed to foreign actions.
Special thanks to @mpolitzer and @fmoura for the insight. :pray:
> ci: tag changesets action by commit SHA

- onchain/rollups/contracts/library/LibOutputValidation.sol
- onchain/rollups/test/foundry/dapp/Application.t.sol
- onchain/rollups/test/foundry/util/LibServerManager.sol
> refactor: use `abi.encode` and remove dead code

- onchain/rollups/test/foundry/inputs/InputBox.t.sol
This test case was taking 30 seconds on my machine.
For testing large inputs, you don't need to make `chainId` a fuzzy parameter.
So, I made it constant, with value `1`.
Now it's taking 2 seconds.
> test: improve `InputBox` test performance

- onchain/rollups/contracts/dapp/Application.sol
- onchain/rollups/contracts/library/LibOutputValidityProof.sol
- onchain/rollups/test/foundry/dapp/Application.t.sol
> refactor!: rename `LibOutputValidation` as `LibOutputValidityProof`

- onchain/rollups/.changeset/fast-tips-push.md
- onchain/rollups/.changeset/fifty-keys-tickle.md
- onchain/rollups/.changeset/lazy-gorillas-scream.md
- onchain/rollups/.changeset/lemon-rivers-nail.md
- onchain/rollups/.changeset/quiet-guests-greet.md
- onchain/rollups/.changeset/red-wasps-report.md
- onchain/rollups/.changeset/rude-scissors-try.md
- onchain/rollups/.changeset/seven-teachers-behave.md
- onchain/rollups/.changeset/silly-islands-end.md
- onchain/rollups/.changeset/smooth-ducks-trade.md
- onchain/rollups/.changeset/two-mails-marry.md
- onchain/rollups/.changeset/wise-owls-push.md
- `IInputRelay` -> `IPortal`
- `InputRelay` -> `Portal`
- `inputRelays` -> `portals`
- `getInputRelays` -> `getPortals`
- `DAppAddressRelay` was removed, not renamed
> chore: adjust changeset files

- .github/workflows/test.yml
- .gitignore
- .prettierignore
- README.md
- package.json
- test/foundry/dapp/Application.t.sol
Also removes several legacy lines in `.gitignore` and `.prettierignore`.
Closes #280
> refactor: remove `pnpm test` script

- .github/workflows/release.yml
- .github/workflows/upload-artifacts.yml
Apparently, the `softprops/action-gh-release` action needs to be run on a workflow triggered by a push to a version tag.
> ci: fix contract artifact upload

- foundry.toml
This reverts commit 086e7755b63dea44325561eecf831896f7b29d9e.
According to Foundry documentation, the default value of the `out` dir is `out`, but, in actuality, it is `artifacts`...
I've opened a PR to fix their docs (https://github.com/foundry-rs/book/pull/1337)
> chore: revert "use default output directory"

- contracts/library/LibAddress.sol
- test/dapp/Application.t.sol
As of now, trying to execute a voucher that transfers more value than the contract balance reverts with an empty return byte array. This can be very hard to debug. We can anticipate this error and raise a nicely formatted custom error instead.
> feat: add `InsufficientFunds` error

- contracts/consensus/AbstractClaimSubmitter.sol
- contracts/consensus/IClaimSubmitter.sol
- contracts/consensus/IConsensus.sol
- contracts/consensus/authority/Authority.sol
- contracts/consensus/authority/IAuthority.sol
- contracts/consensus/quorum/IQuorum.sol
- contracts/consensus/quorum/Quorum.sol
- contracts/dapp/Application.sol
- contracts/dapp/IApplication.sol
- contracts/library/LibOutputValidityProof.sol
- test/consensus/authority/Authority.t.sol
- test/consensus/quorum/Quorum.t.sol
- test/dapp/Application.t.sol
- test/util/LibEmulator.sol
- Create `IClaimSubmitter` interface
- Move definitions from `IConsensus` to `IClaimSubmitter`, leaving just the `isOutputsMerkleRootValid` function (former `wasClaimAccepted`)
- Make `IConsensus` inherit from ERC-165 interface
- Make consensus contracts implement ERC-165 (supporting `IClaimSubmitter`, `IAuthority`, and `IQuorum`, where applicable)
- Adjust nomenclature to make it explicit that the claim is the outputs Merkle root
> refactor: split `IConsensus` interface into two

- .github/actions/setup/action.yml
- foundry.toml
We used to provide a fixed pnpm version on the CI, but this is no longer necessary.
Thanks to the `packageManager` field on the `package.json` file, the version is detected automatically.
Since October 2024, Node.js 20 moved into "Maintenance" phase.
This PR changes CI to use [Node.js 22](https://nodejs.org/en/blog/announcements/v22-release-announce), which is currently in "Active" phase.
This PR also bumps Foundry from 0.3.0 to 1.0.0 (the latest stable release).
See the [migration guide](https://book.getfoundry.sh/guides/v1.0-migration).
One notable breaking change is that the Solidity optimizer is off by default.
So, we have to turn it on explicitly on the `foundry.toml` file.
It is suggested to bump `forge-std` to the latest version because of cheat codes.
> Bump dependencies

- onchain/rollups/cannonfile.toml
- onchain/rollups/package.json
- onchain/rollups/yarn.lock
Adds a cannonfile for rollups v1 contracts.
Depends on `cartesi-util` package already published at https://usecannon.com/packages/cartesi-util
> Cannon for Rollups V1

- .github/workflows/release.yml
Doing `yarn symlink` before `yarn changeset publish` makes the package build process fail.
> ci: do not create symlinks when publishing package

- .github/workflows/release.yml
- onchain/rollups/.changeset/early-colts-smash.md
With symlinks, library paths don't need to be prefixed with `node_modules/`.
Tested locally, and the package builds fine.
> fix: rust bindings build on CI

- package.json
Also, remove hash from `packageManager` field.
> chore: bump pnpm from 9.9.0 to 10.6.1

- .github/actions/setup/action.yml
- .github/dependabot.yaml
- .github/workflows/check-code-format.yml
- .github/workflows/check-commit-messages.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/upload-artifacts.yml
This pull request includes changes to update various GitHub Actions to specific commit hashes for better stability and reproducibility and mitigate supply chain attacks. Additionally, a new Dependabot configuration file has been added to automate dependency updates.
See: https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash
---
Updates to GitHub Actions:
* [`.github/actions/setup/action.yml`](diffhunk://#diff-9fb8259afcb532c9556e2d41ae1ee97cf6de54b486cef93a7ef1bf39433fa530L12-R14): Updated `pnpm/action-setup` to commit `a3252b78c470c02df07e9d59298aecedc3ccdd6d` and `actions/setup-node` to commit `cdca7365b2dadb8aad0a33bc7601856ffabcc48e`.
* [`.github/actions/setup/action.yml`](diffhunk://#diff-9fb8259afcb532c9556e2d41ae1ee97cf6de54b486cef93a7ef1bf39433fa530L28-R28): Updated …
> Pin GH Actions

- .gitignore
- foundry.toml
- test/consensus/authority/Authority.t.sol
- test/consensus/authority/AuthorityFactory.t.sol
- test/consensus/quorum/Quorum.t.sol
- test/consensus/quorum/QuorumFactory.t.sol
- test/dapp/Application.t.sol
- test/dapp/ApplicationFactory.t.sol
- test/dapp/SelfHostedApplicationFactory.t.sol
- test/inputs/InputBox.t.sol
- test/library/LibError.t.sol
- test/library/LibMerkle32.t.sol
- test/portals/ERC1155BatchPortal.t.sol
- test/portals/ERC1155SinglePortal.t.sol
- test/portals/ERC20Portal.t.sol
- test/portals/ERC721Portal.t.sol
- test/portals/EtherPortal.t.sol
- test/util/ERC165Test.sol
- test/util/LibAddressArray.sol
- test/util/LibAddressArray.t.sol
- test/util/OwnableTest.sol
This change apparently improves support by code editors and Solidity plugins.
> chore: make Soldeer generate remappings.txt

- .changeset/shiny-frogs-go.md
- src/dapp/Application.sol
- src/dapp/IApplication.sol
- src/inputs/InputBox.sol
- test/dapp/Application.t.sol
- test/dapp/ApplicationFactory.t.sol
This function aims to improve the node's capability of listening to events emitted by the `Application` contract, for those deployed many blocks after the `InputBox` contract.
This PR also makes some small related improvements.
> Add `getDeploymentBlockNumber` function to `IApplication` interface

- .changeset/clean-sheep-dress.md
- src/consensus/AbstractConsensus.sol
- src/consensus/IConsensus.sol
- src/consensus/authority/Authority.sol
- src/consensus/quorum/Quorum.sol
- src/dapp/Application.sol
- src/dapp/IApplication.sol
- test/consensus/authority/Authority.t.sol
- test/consensus/quorum/Quorum.t.sol
- test/dapp/Application.t.sol
This PR aims to bring a more consistent nomenclature for events.
We are favoring here event names ending with a verb in simple past tense.
> refactor!: rename events

- .changeset/nine-poems-burn.md
- .changeset/petite-numbers-read.md
- .changeset/sweet-tools-taste.md
- foundry.toml
- src/consensus/AbstractConsensus.sol
- src/consensus/IConsensus.sol
- src/consensus/authority/Authority.sol
- src/consensus/quorum/IQuorum.sol
- src/consensus/quorum/Quorum.sol
- test/consensus/authority/Authority.t.sol
- test/consensus/quorum/Quorum.t.sol
This PR adds the following checks to `Authority` and `Quorum`:
- `lastProcessedBlockNumber < block.number`: validators cannot process blocks in the future
- `lastProcessedBlockNumber % epochLength == (epochLength - 1)`: validators have to validate blocks until the last block of an epoch
- there cannot be two accepted claims for the same epoch
The last point is implemented differently for `Authority` and `Quorum`:
- Authority stores the set of epochs for which a claim was accepted.
- Quorum stores the set of validators that have submitted a claim for a given epoch.
Both contracts use OpenZeppelin's bitmap data structure to store sets.
In Authority, epochs are identified by their number (`lastProcessedBlockNumber / epochLength`)
In Quorum, validators are identified by their ID.
Because of …
> Add additional checks to consensus contracts

- .changeset/dull-ravens-relax.md
- .soldeerignore
The problem seemed to be caused by the fact that the Soldeer package included the files `.soldeerignore` and `.gitignore`, which are considered sensitive by Soldeer (although they are not). Soldeer emits a warning and expects the user to choose between yes and no. Since the command is run on the terminal, it raises an IO error, because there is no terminal present.
This PR adds these files to the `.soldeerignore` file so that they are not included in the Soldeer package. These files shouldn't be necessary for users of the Soldeer package, because `.soldeerignore` serves just during the Soldeer package publishing process, and `.gitignore` is only used when git "sees" the directory, but the `dependencies` directory is usually included in the `.gitignore` either way.
This PR also instructs …
> fix: add dotfiles to `.soldeerignore`
